#!/usr/bin/php -q
<?php

require_once 'vendor/autoload.php';

use Testit\App;
use Tests\Asserts\Financial\DocumentType;
use Tests\Asserts\Financial\StandardHistory;

$app = new App([
    'root' => __DIR__,
    'environment' => 'contasobcontrole.com.br',
    'domain' => 'dev.contasobcontrole.com.br',
    'url' => 'http://dev.contasobcontrole.com.br:9010',
    'tests' => [
        StandardHistory::class,
        DocumentType::class
    ],
    'defaults' => [
        'Headers' => [
            'Origin' => 'http://dev.contasobcontrole.com.br:9000'
        ],
    ],
    'cookies' => []
]);

$app->run($argv);