#!/usr/bin/php -q
<?php

require_once 'vendor/autoload.php';

use Simples\Test\App;

$app = new App([
    'root' => __DIR__,
    'environment' => env('TEST_ENVIRONMENT'),
    'domain' => env('TEST_DOMAIN'),
    'url' => env('TEST_URL'),
    'tests' => config('test.tests'),
    'defaults' => [
        'Headers' => [
            'Origin' => env('TEST_ORIGIN')
        ],
    ],
    'cookies' => []
]);

try {
    /*
     * run the App
     */
    $app->run($argv);
} catch (Throwable $error) {
    echo PHP_EOL, 'ERROR ~> ', PHP_EOL;
    echo '    Message .: ', $error->getMessage(), PHP_EOL;
    echo '    File ....: ', $error->getFile(), PHP_EOL;
    echo '    Line ....: ', $error->getLine(), PHP_EOL;
    echo '--------------------------------------------', PHP_EOL, $error->getTraceAsString(), PHP_EOL;
}
